[Terry N.] prevent annoying repeating failure on OS X:
INFO [org.netbeans.core.startup.layers.BinaryFS]: value = org.openide.loaders.DataLoaderPool.factory from Loaders/model/x3d+xml/Factories/org-web3d-x3d-X3DDataObject.instance
java.lang.NoSuchMethodException: org.web3d.x3d.X3DDataObject.<init>(org.openide.filesystems.FileObject, org.openide.loaders.MultiFileLoader)
	at java.lang.Class.getConstructor0(Class.java:3082)
	at java.lang.Class.getConstructor(Class.java:1825)
	at org.openide.loaders.MimeFactory.<init>(MimeFactory.java:78)
Caused: java.lang.IllegalStateException: org.web3d.x3d.X3DDataObject.<init>(org.openide.filesystems.FileObject, org.openide.loaders.MultiFileLoader)

Even though a UniFileLoader is a subclass of MultiFileLoader, something in the NB Classpatholgy is looking explicity for a MultiFileLoader.  This fixes the issue